version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./volumes/zookeeper/data:/var/lib/zookeeper/data
      - ./volumes/zookeeper/log:/var/lib/zookeeper/log
      - ./volumes/zookeeper/secrets:/etc/zookeeper/secrets
  kafka-broker:
    container_name: kafka-broker
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - 9092:9092
    volumes:
      - ./volumes/kafka/data:/var/lib/kafka/data
      - ./volumes/kafka/secrets:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 600000  # 10 minutos x 60 segundos x 1000 ms
    depends_on:
      - zookeeper
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    restart: always
    ports:
      - 5001:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper: 2181
    depends_on:
      - kafka-broker
  init-kafka:
    container_name: init-kafka
    image: confluentinc/cp-kafka:7.0.1
    command: '/kafka/init.sh'
    environment:
      KAFKA_BROKER: kafka-broker:29092
      TOPIC_NAME: git-events
      TOPIC_NAME_RESULTS: git-events-results
    volumes:
      - ./kafka:/kafka
    depends_on:
      - kafka-broker
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0
    ports:
      - 5002:8080
    environment:
      KEYCLOAK_ADMIN: guest
      KEYCLOAK_ADMIN_PASSWORD: guest
    command: 
      - start-dev 
      - --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./api/src:/home/node/api/src
      - ./api/node_modules:/home/node/api/node_modules
    environment:
      NODE_ENV: development
      APP_NAME: API
      PORT: 4000
      LOG_FILENAME: api
      ENABLE_LOG_FILE: 'false'
      KAFKA_CLIENT_ID: git-events
      KAFKA_BROKER: kafka-broker:29092
      KAFKA_TOPIC: git-events
      KAFKA_TOPIC_RESULTS: git-events-results
      KAFKA_GROUP_ID: api-consumer
    depends_on:
      - kafka-broker
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./worker/Dockerfile.dev
    volumes:
      - ./worker/src:/home/node/worker/src
      - ./worker/node_modules:/home/node/worker/node_modules
      - ./volumes/worker/files:/home/node/worker/files
    environment:
      NODE_ENV: development
      APP_NAME: WORKER
      LOG_FILENAME: worker
      ENABLE_LOG_FILE: 'false'
      KAFKA_CLIENT_ID: git-events
      KAFKA_BROKER: kafka-broker:29092
      KAFKA_TOPIC: git-events
      KAFKA_TOPIC_RESULTS: git-events-results
      KAFKA_GROUP_ID: worker-consumer
      FILE_DIR: './files'
    depends_on:
      - kafka-broker
  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: ./front-end/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/usr/src/app/front-end
      - ./front-end/node_modules:/usr/src/app/front-end/node_modules
    stdin_open: true
    environment:
      WATCHPACK_POLLING: 'true'
      CHOKIDAR_USEPOLLING: 'true'
      PUBLIC_URL: http://localhost:3000
      REACT_APP_KEYCLOAK_REALM: SAD
      REACT_APP_KEYCLOAK_URL: http://localhost:5002
      REACT_APP_KEYCLOAK_CLIENT_ID: sad-git-executor
      REACT_APP_GRAPHQL_ENDPOINT: http://localhost:4000
      NODE_ENV: development
    depends_on:
      - api
      - keycloak