# node:18.13.0-alpine
FROM node@sha256:09faa7dabeae557cb6baff17be5b216fc4e3c9608aa04fe71695aad3d229a9c7

RUN mkdir -p /home/node/worker/node_modules \
  && chown -R node:node /home/node/worker 

WORKDIR /home/node/worker

RUN apk update

RUN apk add git

COPY ./worker/package*.json ./

COPY ./worker .

RUN npm install

CMD ["npm", "run", "dev"]