# node:18.13.0-alpine
FROM node@sha256:09faa7dabeae557cb6baff17be5b216fc4e3c9608aa04fe71695aad3d229a9c7

RUN mkdir -p /home/node/api/node_modules \
  && chown -R node:node /home/node/api 

WORKDIR /home/node/api

COPY ./api/package*.json ./
COPY ./api .

RUN npm install

EXPOSE 4000

CMD ["npm", "run", "dev"]